### ISSUE TITLE
iOS9 관련 옵션 설명이 없습니다.

### ISSUE THREAD

**Issue by flyskyko** [nhnent/tui.component.m-app-loader#1]
`useIOS9`과 `syncToIOS9` 옵션 설명 업데이트 부탁드려요.

**Comment by minkyu-yi** [comment]
네, 조만간 업데이트하도록 하겠습니다.

**Comment by dongwoo-kim** [comment]
Works Mobile - https://www.worksmobile.com
--------------------------------------------
김동우(dongwoo.kim@nhnent.com) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [tui.component.m-app-loader] iOS9 관련 옵션 설명이 없습니다. (#1)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김동우(dongwoo.kim@nhnent.com) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-11-09 09:30 ~ 2015-11-23 18:30 GMT +09:00]<br>2015.11.09 ~2015.11.23 부재입니다.<br><br>그리드 관련 문의:  그리드 DL(dl_grid@nhnent.com)<br>업무 위임자 : FE개발팀 이민규<br>
--------------------------------------------
